package com.bettingproject.identity.domain;

public enum NormalizationAnomalyCode {
    MISSING_MAPPING,
    AMBIGUOUS_MAPPING,
    REJECTED_MAPPING,
    MAPPING_CONFLICT,
    UNASSIGNED_AUTHORITY,
    CONTROL_WITHOUT_PRIMARY,
    CONTROL_DIVERGENCE,
    STALE_OBSERVATION,
    EQUAL_AUTHORITY_TIME_CONFLICT,
    INVALID_TRANSITION,
    PARTICIPANT_ORDER_CONFLICT,
    AMBIGUOUS_FIXTURE_IDENTITY,
    INVALID_FIXTURE,
    LEGACY_SCHEMA_NOT_NORMALIZABLE,
    UNSUPPORTED_SCHEMA,
    INVALID_SNAPSHOT
}
