package com.bettingproject.qualification.domain;

public enum QualityIssueCode {
    MISSING_PLAYER_FULL_NAME,
    ZERO_MINUTE_EXPECTED_METRICS,
    INVALID_SECOND_YELLOW_VALUE,
    MISSING_PLAYER_YELLOW_CARD,
    CROSS_ENDPOINT_PLAYER_ID_MISMATCH,
    EMPTY_RESPONSE_WITH_HISTORICAL_REGRESSION,
    FINAL_SCORE_CONFLICT
}
