package com.bettingproject.collection.adapter.web.j7;

/** Safe, payload-free protocol failure categories. */
public enum J7ImportProtocolError {
    MISSING_HEADER,
    DUPLICATE_HEADER,
    INVALID_CONTENT_TYPE,
    INVALID_ACCEPT,
    INVALID_CONTENT_ENCODING,
    INVALID_TRANSFER_ENCODING,
    INVALID_CONTENT_LENGTH,
    CONTENT_LENGTH_MISMATCH,
    INVALID_PROTOCOL_VERSION,
    INVALID_EXPORT_ID,
    INVALID_CANONICAL_EVENT_ID,
    INVALID_PROVIDER_EVENT_ID,
    INVALID_TIMESTAMP,
    INVALID_GENERATOR_VERSION,
    INVALID_SHA256,
    INVALID_IDEMPOTENCY_KEY,
    INVALID_UTF8,
    INVALID_JSON,
    NON_CANONICAL_CONTENT,
    INVALID_SCHEMA,
    INVALID_SCHEMA_ID,
    INVALID_SCHEMA_VERSION,
    INVALID_VALIDATION_STATUS,
    INVALID_VALIDATION_TIME,
    IDENTITY_MISMATCH,
    INVALID_FILE_HASH,
    INVALID_DATA_HASH,
    INVALID_SOURCE_SET_HASH
}
